### ISSUE TITLE
Add Translation System (v3.8.0)

### ISSUE THREAD

**Issue by JaWarrior12** [JaWarrior12/New-Light#112]
# Translation Feature
Add auto-translate to New Light

## To-Do:
- [x] Configurable channels (Translate to multiple langs & channels)
- [x] Send images and **Maybe** formatting
- [x] Work with replies, ping instead
- [x] A translate command
- [x] __**FILTERING FILTERING FILTERING!!!!!!!!**__ Filter slurs and other such terms, DO NOT TRANSLATE that crap

**Comment by JaWarrior12** [comment]
MAYBE, use this for detection: https://github.com/detectlanguage/detectlanguage-python
Though, hasn't been really updated in years.

**Comment by JaWarrior12** [comment]
# Requirements:
- Flexible, translate to multiple languages depending on server's needs
- Updatable list of active languages
- Send images, gifs, formatting
- Ping the replied to user (keep replies working) as a silent ping in translated to channels (so you don't get pinged 17 times)

**Comment by JaWarrior12** [comment]
Use this code excerpt:
```python
text = 'happy coding'
translated = MicrosoftTranslator(api_key='some-key', target='de').translate(text=text) # Base
translated_two_targets = MicrosoftTranslator(api_key='some-key', target=['de', 'ru']).translate(text=text) # Translate to multiple languages
translated_with_optional_attr = MicrosoftTranslator(api_key='some-key', target='de', textType='html']).translate(text=text) # Meh, don't see a use
```

**Comment by JaWarrior12** [comment]
This excerpt gets supported langs with their codes.
```python
# default return type is a list
langs_list = GoogleTranslator().get_supported_languages()  # output: [arabic, french, english etc...]

# alternatively, you can the dictionary containing languages mapped to their abbreviation
langs_dict = GoogleTranslator().get_supported_languages(as_dict=True)  # output: {arabic: ar, french: fr, english:en etc...}
```

**Comment by JaWarrior12** [comment]
Finally found a library to do this, work has begun and I hope to have the system done within 3 weeks.

**Comment by JaWarrior12** [comment]
12/20/24
---------------------
Started Work on auto-translate. Now I just need to test and tweak
