### ISSUE TITLE
Econ Commands Updates (v.3.8.0)

### ISSUE THREAD

**Issue by JaWarrior12** [JaWarrior12/New-Light#121]
# Update Econ Commands
To match the needs of the current dred community,  I need to update this cog. 

### Key Needs:
- Formatting
- Clear Output (See formatting, also output into text files for easier uploading)
- Broader search range
- Easier syntax
- New commands/turn some of the loops into commands (Like Transfer Log Loop)

### To-Do List
- [ ] I need to format the output, the spewage that the `n!hex` command spits out is not at all helpful. 
- [ ] I also need to make a command that does the same function as the transfer log loop, I use that function enough that I need an easy way to do it. 
- [ ] _**Possibly**_ add a function to read the ship list data, I will never make it easy to just spy on folks, but this functionality could be helpful in rooting out spies.
- [ ] _**Maybe**_ make a mapping command? This would get a map of ships up to a given distance (branch amount/number) after being given a single hex code.
- [ ] _**HIGHLY UNLIKELY**_ Maybe start mapping ships? A database of who owns what could be helpful for trading/tracking stolen stuff; but, I do not want HL style spyware.

**Comment by JaWarrior12** [comment]
With the ship list submit command, it's a server/user whitelist. So the user can pick specific people and servers that can read their ship list. Now, I am debating whether or not an emergency get-ship command (this would be to get the owner/caps of a ship currently getting griefed) can override the whitelist.

**Comment by JaWarrior12** [comment]
Ship list submit command is underway, not going to do mapping on New Light (Might do it on another bot because runtime).

**Comment by JaWarrior12** [comment]
Still need to work on ssl Cmd. as well as cmds to read the stored sl's
