### ISSUE TITLE
Plexus System Changes (v3.8.0)

### ISSUE THREAD

**Issue by JaWarrior12** [JaWarrior12/New-Light#123]
# Changes to the Plexus Systems cog (Daily Transfer Logs in the Help Command panel)

### To-Do:
- [x] Rename it, it's open to everyone
- [x] Rework the cog description, it will do more than just transfer logs. (Ideas in a post below)
- [x] Better Formatting of the logs? Idk, this will be put to polls.
- [x] Remove the `thread.purge` line in the Daily Inventory Report function. I'd prefer to keep past data saved to make it way easier to compare between days.

**Comment by JaWarrior12** [comment]
Completed with remoteWork-dev-branch commit 718acff
