### ISSUE TITLE
Dev Commands Update (v3.8.0)

### ISSUE THREAD

**Issue by JaWarrior12** [JaWarrior12/New-Light#125]
# Update Dev Commands
I need some more access with dev commands. I need to be able to remotely update settings for servers.

### To-Do:
- [x] Command to remotely change server config settings
- [ ] _**Hopefully**_ & finally update my metrics. I want to be able to see weekly/monthly/yearly trends for individual servers and overall. _**Maybe**_ do per command/cog as well to see what gets used the most and see where I should focus my time.
- [x] Command to check perms in a server/channel. I need to be able to troubleshoot any potential situation without needing perms in a server
- [x] Logging errors in a channel on dev server (Scrapped For Now, Requires A Lot Of Reworking of all Try/Except blocks

**Comment by JaWarrior12** [comment]
12/20/24
- Added a command to update the list of keys for every guild in a db file.

**Comment by JaWarrior12** [comment]
Move Metrics to a new JSON file for metrics alone. I need a dedicated file for the amount of info I want to store

**Comment by JaWarrior12** [comment]
Push back metrics update. Still not sure how I want to go about it.
