### ISSUE TITLE
Fix Member List

### ISSUE THREAD

**Issue by JaWarrior12** [JaWarrior12/New-Light#128]
# Fix Member List!!!
Memlist currently displays admin/mod roles (it shouldn't) along with listing people multiple times. Also breaks when it hits the message character limit. This is gonna require a full rewrite of the function.

### To-Do:
- [x] Fix the members not being displayed only once (under highest role) [Scrapped]
- [x] _**MAYBE**_ go to a list of roles instead of the current system. A list would be easier on server side but a bit harder to setup client side. [Decision: Keep Current System]
- [x] Make it SILENT pings. Idfk why it isn't doing silent pings, but it damn well needs to.
- [x] Make it split into multiple messages to avoid the char limit. This is where SILENT PINGS are really really really important.

**Comment by JaWarrior12** [comment]
Silent doesn't do anything, so fixed the ping/notification issue by sending a message and then editing the memlist content into it.

**Comment by JaWarrior12** [comment]
It works flawlessly in other servers, probably just some mess with my dev server role order that is screwing stuff up.

**Comment by JaWarrior12** [comment]
Completed to satisfaction. Not going to move to a role list and displaying members multiple times is acceptable.
